#Model Parameters
state_vector_size: 6
observation_vector_size: 3

#Data Split
train_set_size: 150
CV_set_size: 250
test_set_size: 250
batch_size: 1
force_batch: [4] #For debug
train: true
test_mode: FW + BW

#Training Scheduler
wd: 1.0e-3
first_phase_id: 1
spoon_feeding : 0
training_scheduler:
  '0':
    mode: FW
    lr: 1.0e-3
    n_epochs: 20
    max_train_sequence_length: -1
  '1':
    mode: BW
    lr: 1.0e-3
    n_epochs: 10
    max_train_sequence_length: 22



#Parameters for Neural Network
use_cuda: false
input_dim_mult_KNet: 5
output_dim_mult_KNet: 40
input_dim_mult_RTSNet: 5
output_dim_mult_RTSNet: 40


# #Paths

path_results: "Simulations/Particle_Tracking/models"
Dataset_path: "Simulations\\Particle_Tracking\\data\\Dataset_Debug_09_05_24__18_41.pt"