#Model Parameters
state_vector_size: 6
observation_vector_size: 3

#Data Split
train_set_size: 1000
CV_set_size: 1000
test_set_size: 1000
batch_size: 50
interpolation_points_to_add : 0 # number of points to add between every 2 clusters for backward pass
force_batch: [] #For debug
train: false
test_mode: FW + BW
model_path: Simulations/Particle_Tracking/runs/D25_M05_h08_m36/models/best-model-weights_FINAL.pt #When null takes the default model from the run #

#Training Scheduler
wd: 1.0e-3
first_phase_id: 0
num_runs : 3 #Runs in Final Eval
max_energy_to_rerun: 1.5 #All trajectories with estimated energy under this value will be rerun 
training_scheduler:
  '0':
    mode: FW
    lr: 1.0e-3
    n_epochs: 10
    spoon_feeding : 10
  '1':
    mode: FW
    lr: 1.0e-3
    n_epochs: 20
  '2':
    mode: BW
    lr: 1.0e-3
    n_epochs: 25
    loss: velocity
  '3':
    mode: BW
    lr: 5.0e-4
    n_epochs: 20
    loss: velocity
  '4':
    mode: FW + BW
    lr: 1.0e-4
    n_epochs: 20
    loss: velocity


################
## loss types ##
################
# all (default) - loss between all of the state vectors
# velocity - loss only on the velocities of the first state vector
# energy - loss only on the intial energy trajectory
# interpolation - loss only on the added interpolated space state vectors




#Parameters for Neural Network
use_cuda: false
input_dim_mult_KNet: 5
output_dim_mult_KNet: 40
input_dim_mult_RTSNet: 5
output_dim_mult_RTSNet: 40


# #Paths

path_results: Simulations/Particle_Tracking
Dataset_path: Simulations/Particle_Tracking/data/point4-3Mev_Dataset_150points_19_05_24__20_25.pt # Train / CV
test_set_path: Simulations/Particle_Tracking/data/point-3Mev_Dataset_16_05_24__19_17.pt # Test