#Model Parameters
state_vector_size: 6
observation_vector_size: 3

#Data Split
train_set_size: 150
CV_set_size: 250
test_set_size: 250
batch_size: 1
force_batch: [] #For debug
train: true
test_mode: FW + BW

#Training Scheduler
wd: 1.0e-3
first_phase_id: 0
training_scheduler:
  '0':
    mode: FW
    lr: 1.0e-3
    n_epochs: 50
    max_train_sequence_length: -1
  '1':
    mode: FW
    lr: 1.0e-4
    n_epochs: 100
    max_train_sequence_length: 75
  '2':
    mode: FW
    lr: 1.0e-4
    n_epochs: 100
    max_train_sequence_length: 125
  '3':
    mode: FW
    lr: 1.0e-4
    n_epochs: 100
    max_train_sequence_length: 175
  '4':
    mode: FW
    lr: 1.0e-4
    n_epochs: 50
    max_train_sequence_length: 225
  '5':
    mode: FW
    lr: 1.0e-6
    n_epochs: 50
    max_train_sequence_length: -1
  '6':
    mode: BW
    lr: 5.0e-4
    n_epochs: 50
    max_train_sequence_length: -1




#Parameters for Neural Network
use_cuda: false
input_dim_mult_KNet: 5
output_dim_mult_KNet: 40
input_dim_mult_RTSNet: 5
output_dim_mult_RTSNet: 40


# #Paths

path_results: "Simulations/Particle_Tracking/models"
Dataset_path: "Simulations\\Particle_Tracking\\data\\Dataset_Debug_09_05_24__18_41.pt"