max_traj_length : 2000
stopping_power_table_path : "Tools/stpHydrogen_new.txt"
delta_t : 0.01 #ns
charge_std_x_axis : 0.2 # STD of diffusion in the x axis
charge_std_y_axis : 0.2 # STD of diffusion in the y axis

#Config Parameters for Chamber
magnetic_field : 2.85 #T
electric_field : 500 #V/m
gas_density : 0.033 #mg/cm3 at 1 bar
sensor_sampling_rate_Mhz : 3.125 # [Mhz] 
chamber_length : 100 #[cm]

##Config Parameters for Pad
small_z_spacing : 0.00508 # 2 * 2.54 / 1000
small_tri_side : 0.46736 # 184. * 2.54 / 1000
umega_radius : 27.50000088 # 10826.772 * 2.54 /1000


########################
### Simulation Modes ###
########################

CoM_observations : true #if set to true, observations will be taken from a CoM of the energy cloud. Otherwise, closest pad from real XY

mode: "generate_dataset" # "generate_dataset" - generate a whole dataset // "generate_traj" - generate 1 trajectory

##Config Parameters for "generate_dataset"
num_train_traj : 100
num_val_traj: 20
num_test_traj : 0
sub_sample_rate_data: 5

dataset_name : "10-15Mev_Dataset_120points"
output_dir : "Simulations/Particle_Tracking/data" # where to save results
angle_energy_table_path : Tools/Angle_Energy_10Mev-15Mev.txt

##Config Parameters for "generate_traj"
energy :  0.3579999999999 #MeV
theta : 1.40713822625604 #rad
phi : -0.644949248687716 #rad
plot_traj: true #Flag if to plot trajectories, plots chosen trajectory one on top of the other. If this is false, disables the rests
plot_real_traj : true # flag if to plot the real trajectory
plot_observed_traj : true # flag if to plot observed trajectory
plot_energy_on_pad : true # flag if to plot energy on pad


